#!/bin/bash

source /etc/profile
java=$(which java)
JPOSTGREY_JAR=/opt/jpostgrey/jpostgrey.jar

LOGCONFIG=/etc/jpostgrey/logging.conf

if [[ -f "$LOGCONFIG" ]]; then
    LOGOPTS="-Dlog4j.configuration=file:/etc/jpostgrey/logging.conf"
fi

$java $LOGOPTS -jar ${JPOSTGREY_JAR}