#!/bin/sh

### BEGIN INIT INFO
# Provides:       jpostgrey
# Required-Start: $network $remote_fs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description:    Start the jPostgrey daemon
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

prog=jpostgrey

PIDFILE=/var/run/jpostgrey/jpostgrey.conf
CONFIGFILE=//home/oxmox/workspace/jpostgrey/data/jpostgrey.conf

OPTIONS="-p $PIDFILE -c $CONFIGFILE"

JPOSTGREY=/usr/share/jpostgrey/jpostgrey

do_restart_sanity_check()
{
        $SSHD -t
        RETVAL=$?
        if [ $RETVAL -ne  0 ]; then
                failure $"Configuration file or keys are invalid"
                echo
        fi
}

start()
{
        [ -x $JPOSTGREY ] || exit 5
        [ -f $CONFIFILE ] || exit 6

        echo -n $"Starting $prog: "
        $JPOSTGREY $OPTIONS && success || failure
        RETVAL=$?
        echo
        return $RETVAL
}
stop()
{
        echo -n $"Stopping $prog: "
        killproc -p $PID_FILE $JPOSTGREY
        RETVAL=$?
        echo
}
restart() {
        stop
        start
}
rh_status() {
        status -p $PID_FILE jpostgrey
}
rh_status_q() {
        rh_status >/dev/null 2>&1
}


case "$1" in
    start)
		rh_status_q && exit 0
		start
		;;
    stop)
		if ! rh_status_q; then
			rm -f $PIDFILE
			exit 0
		fi
		stop
		;;
    restart)
    	restart
    	;;
    status)
		rh_status
		RETVAL=$?
		;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=2
        ;;
esac
exit $RETVAL