#!/bin/bash

source /etc/profile
java=$(which java)
JPOSTGREY_JAR=/usr/share/jpostgrey/jpostgrey.jar

if [[ $* =~ .*DAEMON.* ]]; then
	RUNMODE=DAEMON
fi

# Setting defaults
if [[ -z "${PIDFILE}" ]]; then
	PIDFILE=/tmp/jpostgrey.pid
fi

if [[ -z "${CONFIGFILE}" ]]; then
	CONFIGFILE=/etc/jpostgrey.conf
fi

echo "RUNMODE: $RUNMODE"

if [[ "${RUNMODE}" == "DAEMON" ]]; then
	nohup $java -Dlog4j.configuration=file:/etc/jpostgrey/logging.conf -jar ${JPOSTGREY_JAR} -p ${PIDFILE} $* &
	sleep 2
else
	$java -Dlog4j.configuration=file:/etc/jpostgrey/logging.conf -jar ${JPOSTGREY_JAR} -p ${PIDFILE} -c ${CONFIGFILE} $*
fi
